# Generated by Django 4.1.1 on 2022-10-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
