# Generated by Django 4.1.1 on 2022-10-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shop_alter_contact_us_company_name_product_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('300 TO 500', '300 TO 500'), ('500 TO 700', '500 TO 700'), ('700 TO 1000', '700 TO 1000'), ('1000 TO 1200', '1000 TO 1200'), ('1200 TO 1500', '1200 TO 1500')], max_length=60)),
            ],
        ),
    ]
