# Generated by Django 4.1.1 on 2022-10-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_filter_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
    ]
